insert into genre (name, description) values ('DRAMA', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into genre (name, description) values ('COMEDY', 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.');
insert into genre (name, description) values ('ROMANCE', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into genre (name, description) values ('THRILLER', 'Phasellus sit amet erat. Nulla tempus.');
insert into genre (name, description) values ('DOCUMENTARY', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into genre (name, description) values ('ACTION', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.');
insert into genre (name, description) values ('HISTORY', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.');
insert into genre (name, description) values ('SCI-FI', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.');
insert into genre (name, description) values ('MUSICAL', 'Sed ante. Vivamus tortor.');
insert into genre (name, description) values ('HORROR', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.');

insert into movie (title, poster, genre_id, pga, description, short_description, release_date, run_time_in_min, average_rating, premiere) values ('Street Without End (Kagirinaki hodo)', 'http://dummyimage.com/100x79.png/ff4444/ffffff', 1, 'X82', 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 'Curabitur convallis.', '2007-10-10', 122, 6.4, false);
insert into movie (title, poster, genre_id, pga, description, short_description, release_date, run_time_in_min, average_rating, premiere) values ('Blue Kite, The (Lan feng zheng)', 'http://dummyimage.com/100x63.png/cc0000/ffffff', 1, 'Y35313', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', 'Aliquam non mauris. Morbi non lectus.', '1984-10-10', 134, 6.8, false);
insert into movie (title, poster, genre_id, pga, description, short_description, release_date, run_time_in_min, average_rating, premiere) values ('Road to Bali', 'http://dummyimage.com/100x67.png/dddddd/000000', 2, 'S27492D', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2002-10-10', 119, 5.4, true);
insert into movie (title, poster, genre_id, pga, description, short_description, release_date, run_time_in_min, average_rating, premiere) values ('Puppet Master 5: The Final Chapter', 'http://dummyimage.com/100x87.png/ff4444/ffffff', 8, 'M86069', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'Nulla ac enim.', '1996-10-10', 122, 6.3, false);
insert into movie (title, poster, genre_id, pga, description, short_description, release_date, run_time_in_min, average_rating, premiere) values ('Ninja: Shadow of a Tear', 'http://dummyimage.com/100x62.png/cc0000/ffffff', 6, 'S83112', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'Duis at velit eu est congue elementum.', '2005-10-10', 136, 5.1, false);
insert into movie (title, poster, genre_id, pga, description, short_description, release_date, run_time_in_min, average_rating, premiere) values ('Anastasia', 'http://dummyimage.com/100x52.png/5fa2dd/ffffff', 6, 'S9492XS', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '1974-10-10', 102, 3.5, true);
insert into movie (title, poster, genre_id, pga, description, short_description, release_date, run_time_in_min, average_rating, premiere) values ('Hot Shots! Part Deux', 'http://dummyimage.com/100x76.png/cc0000/ffffff', 6, 'T8111', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', '2010-10-10', 158, 2.5, false);
insert into movie (title, poster, genre_id, pga, description, short_description, release_date, run_time_in_min, average_rating, premiere) values ('Scream of Stone (Cerro Torre: Schrei aus Stein)', 'http://dummyimage.com/100x72.png/cc0000/ffffff', 1, 'N158', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '1994-10-10', 80, 2.1, true);
insert into movie (title, poster, genre_id, pga, description, short_description, release_date, run_time_in_min, average_rating, premiere) values ('Samson and Delilah', 'http://dummyimage.com/100x89.png/dddddd/000000', 5, 'M9977', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Nulla nisl. Nunc nisl.', '1992-10-10', 97, 0.6, true);
insert into movie (title, poster, genre_id, pga, description, short_description, release_date, run_time_in_min, average_rating, premiere) values ('Just Like Us', 'http://dummyimage.com/100x99.png/ff4444/ffffff', 2, 'H4443', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'Praesent lectus.', '2011-10-10', 129, 8.8, false);
insert into movie (title, poster, genre_id, pga, description, short_description, release_date, run_time_in_min, average_rating, premiere) values ('Mumblecore', 'http://dummyimage.com/100x66.png/dddddd/000000', 3, 'V9087XD', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Vestibulum rutrum rutrum neque.', '1966-10-10', 119, 3.5, true);
insert into movie (title, poster, genre_id, pga, description, short_description, release_date, run_time_in_min, average_rating, premiere) values ('Nightcap (Merci pour le chocolat)', 'http://dummyimage.com/100x61.png/dddddd/000000', 4, 'S92011G', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 'Integer non velit.', '2003-10-10', 121, 6.8, true);
insert into movie (title, poster, genre_id, pga, description, short_description, release_date, run_time_in_min, average_rating, premiere) values ('Twice-Told Tales', 'http://dummyimage.com/100x52.png/ff4444/ffffff', 1, 'S90472S', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '2009-10-10', 142, 4.7, false);
insert into movie (title, poster, genre_id, pga, description, short_description, release_date, run_time_in_min, average_rating, premiere) values ('Daltry Calhoun', 'http://dummyimage.com/100x90.png/dddddd/000000', 2, 'S301XXD', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2008-10-10', 156, 6.5, true);
insert into movie (title, poster, genre_id, pga, description, short_description, release_date, run_time_in_min, average_rating, premiere) values ('Veer Zaara', 'http://dummyimage.com/100x50.png/ff4444/ffffff', 9, 'H401131', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2003-10-10', 157, 7.6, false);
insert into movie (title, poster, genre_id, pga, description, short_description, release_date, run_time_in_min, average_rating, premiere) values ('Legend of Hercules, The', 'http://dummyimage.com/100x80.png/ff4444/ffffff', 6, 'T454X4D', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Fusce posuere felis sed lacus.', '1999-10-10', 94, 1.6, false);
insert into movie (title, poster, genre_id, pga, description, short_description, release_date, run_time_in_min, average_rating, premiere) values ('Good Guy, The', 'http://dummyimage.com/100x50.png/ff4444/ffffff', 2, 'M0517', 'Aliquam erat volutpat. In congue. Etiam justo.', 'Quisque ut erat.', '2009-10-10', 131, 9.7, false);
insert into movie (title, poster, genre_id, pga, description, short_description, release_date, run_time_in_min, average_rating, premiere) values ('Road Trip', 'http://dummyimage.com/100x85.png/dddddd/000000', 2, 'S82263A', 'Quisque ut erat.', 'Donec dapibus.', '2000-10-10', 87, 6.3, true);
insert into movie (title, poster, genre_id, pga, description, short_description, release_date, run_time_in_min, average_rating, premiere) values ('Farewell to Arms, A', 'http://dummyimage.com/100x97.png/dddddd/000000', 3, 'L4059', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', '1991-10-10', 99, 3.6, false);
insert into movie (title, poster, genre_id, pga, description, short_description, release_date, run_time_in_min, average_rating, premiere) values ('Get Shorty', 'http://dummyimage.com/100x97.png/cc0000/ffffff', 4, 'S82861N', 'In hac habitasse platea dictumst.', 'Integer ac leo.', '1996-10-10', 156, 8.8, true);

insert into cinema_room(max_number_of_seats, room_number) values (10, 1);
insert into cinema_room(max_number_of_seats, room_number) values (9, 2);

insert into seat( row_number, seat_number, seats_status, cinema_room_id) values ( 1, 1, 'NORMAL', 1)
insert into seat( row_number, seat_number, seats_status, cinema_room_id) values ( 1, 2, 'NORMAL', 1)
insert into seat( row_number, seat_number, seats_status, cinema_room_id) values ( 1, 3, 'NORMAL', 1)
insert into seat( row_number, seat_number, seats_status, cinema_room_id) values ( 1, 4, 'NORMAL', 1)
insert into seat( row_number, seat_number, seats_status, cinema_room_id) values ( 1, 5, 'NORMAL', 1)
insert into seat( row_number, seat_number, seats_status, cinema_room_id) values ( 2, 1, 'NORMAL', 1)
insert into seat( row_number, seat_number, seats_status, cinema_room_id) values ( 2, 2, 'NORMAL', 1)
insert into seat( row_number, seat_number, seats_status, cinema_room_id) values ( 2, 3, 'NORMAL', 1)
insert into seat( row_number, seat_number, seats_status, cinema_room_id) values ( 2, 4, 'NORMAL', 1)
insert into seat( row_number, seat_number, seats_status, cinema_room_id) values ( 2, 5, 'NORMAL', 1)

insert into seat( row_number, seat_number, seats_status, cinema_room_id) values ( 1, 1, 'NORMAL', 2)
insert into seat( row_number, seat_number, seats_status, cinema_room_id) values ( 1, 2, 'NORMAL', 2)
insert into seat( row_number, seat_number, seats_status, cinema_room_id) values ( 1, 3, 'NORMAL', 2)
insert into seat( row_number, seat_number, seats_status, cinema_room_id) values ( 2, 1, 'NORMAL', 2)
insert into seat( row_number, seat_number, seats_status, cinema_room_id) values ( 2, 2, 'NORMAL', 2)
insert into seat( row_number, seat_number, seats_status, cinema_room_id) values ( 2, 3, 'NORMAL', 2)
insert into seat( row_number, seat_number, seats_status, cinema_room_id) values ( 3, 1, 'NORMAL', 2)
insert into seat( row_number, seat_number, seats_status, cinema_room_id) values ( 3, 2, 'NORMAL', 2)
insert into seat( row_number, seat_number, seats_status, cinema_room_id) values ( 3, 3, 'NORMAL', 2)

insert into users(email, first_name, last_name, role) values ('email@wp.pl', 'testuser1', 'testuser1', 'USER')
insert into auth_users(password, user_id) values ('authuser', 1)

insert into blik(blik_number) values (123456)
insert into blik(blik_number) values (321654)
insert into blik(blik_number) values (987432)

--insert into repertoire(day_of_week, repertoire_date) values ('FRIDAY', '2023-02-10')

--insert into showing(date, show_hour,cinema_room_id,movie_id,repertoire_id) values ('2023-02-16', 12.30, 1, 2, 1)
--insert into showing(date, show_hour,cinema_room_id,movie_id,repertoire_id) values ('2023-02-16', 12.30, 1, 2, 1)
--insert into showing(date, show_hour,cinema_room_id,movie_id,repertoire_id) values ('2023-02-16', 12.30, 1, 1, 1)